use std::fs::File;
use std::io::{self, BufWriter, Write};
use std::path::Path;

use crate::hasher::HashKind;
use crate::model::FileEntry;

/// Write a hash file for the given entries. Format depends on hash kind:
/// - CRC32 (SFV): `filename CRC32VALUE`
/// - Others: `hashvalue *filename`
pub fn write_hash_file(
    entries: &[FileEntry],
    output_path: &Path,
    kind: HashKind,
    uppercase: bool,
) -> io::Result<()> {
    let file = File::create(output_path)?;
    let mut writer = BufWriter::new(file);

    // Header comment
    writeln!(writer, "; Generated by RapidChecksum")?;
    writeln!(writer, ";")?;

    for entry in entries {
        let hash = entry.formatted_hash_value(kind, uppercase);
        if hash.is_empty() {
            continue;
        }

        match kind {
            // SFV format: filename HASH
            HashKind::CRC32 => {
                writeln!(writer, "{} {}", entry.filename, hash)?;
            }
            // Standard hash format: hash *filename (binary mode indicator)
            _ => {
                writeln!(writer, "{} *{}", hash, entry.filename)?;
            }
        }
    }

    writer.flush()?;
    Ok(())
}
