use std::fs::File;
use std::io::{self, BufWriter, Write};
use std::path::Path;

use crate::hasher::HashKind;
use crate::model::FileEntry;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SfvRecord {
    pub filename: String,
    pub crc32: String,
}

/// Read a UTF-8 SFV file from disk.
pub fn read_sfv_file(path: &Path) -> io::Result<Vec<SfvRecord>> {
    let bytes = std::fs::read(path)?;
    let content = String::from_utf8(bytes).map_err(|err| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("SFV file is not valid UTF-8: {err}"),
        )
    })?;

    parse_sfv(&content)
}

/// Parse UTF-8 SFV content.
pub fn parse_sfv(content: &str) -> io::Result<Vec<SfvRecord>> {
    let mut records = Vec::new();

    for (line_number, raw_line) in content.lines().enumerate() {
        let mut line = raw_line.strip_suffix('\r').unwrap_or(raw_line);
        if line_number == 0 {
            line = line.strip_prefix('\u{feff}').unwrap_or(line);
        }

        if line.is_empty() || line.starts_with(';') {
            continue;
        }

        let line = line.trim_end_matches(' ');
        if line.is_empty() {
            continue;
        }

        if line.contains('\t') {
            return Err(invalid_sfv_line(
                line_number + 1,
                "tab characters are not valid in SFV entries",
            ));
        }

        let checksum_start = line.len().checked_sub(8).ok_or_else(|| {
            invalid_sfv_line(line_number + 1, "missing 8-digit CRC32 checksum")
        })?;
        let checksum = &line[checksum_start..];
        if !checksum.bytes().all(|byte| byte.is_ascii_hexdigit()) {
            return Err(invalid_sfv_line(
                line_number + 1,
                "checksum must be exactly 8 hexadecimal characters",
            ));
        }

        let prefix = &line[..checksum_start];
        let filename_end = prefix.trim_end_matches(' ').len();
        if filename_end == prefix.len() {
            return Err(invalid_sfv_line(
                line_number + 1,
                "missing space separator before checksum",
            ));
        }

        let filename = &prefix[..filename_end];
        if filename.is_empty() {
            return Err(invalid_sfv_line(line_number + 1, "missing filename"));
        }

        records.push(SfvRecord {
            filename: filename.to_string(),
            crc32: checksum.to_ascii_uppercase(),
        });
    }

    Ok(records)
}

fn invalid_sfv_line(line_number: usize, message: &str) -> io::Error {
    io::Error::new(
        io::ErrorKind::InvalidData,
        format!("SFV parse error on line {line_number}: {message}"),
    )
}

/// Write a hash file for the given entries. Format depends on hash kind:
/// - CRC32 (SFV): `filename CRC32VALUE`
/// - Others: `hashvalue *filename`
pub fn write_hash_file(
    entries: &[FileEntry],
    output_path: &Path,
    kind: HashKind,
    uppercase: bool,
) -> io::Result<()> {
    let file = File::create(output_path)?;
    let mut writer = BufWriter::new(file);

    // Header comment
    writeln!(writer, "; Generated by RapidChecksum")?;
    writeln!(writer, ";")?;

    for entry in entries {
        let hash = entry.formatted_hash_value(kind, uppercase);
        if hash.is_empty() {
            continue;
        }

        match kind {
            // SFV format: filename HASH
            HashKind::CRC32 => {
                writeln!(writer, "{} {}", entry.filename, hash)?;
            }
            // Standard hash format: hash *filename (binary mode indicator)
            _ => {
                writeln!(writer, "{} *{}", hash, entry.filename)?;
            }
        }
    }

    writer.flush()?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn create_temp_dir(name: &str) -> std::path::PathBuf {
        let unique = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let dir = std::env::temp_dir().join(format!(
            "rapidchecksum-{name}-{}-{unique}",
            std::process::id()
        ));
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn parse_sfv_supports_utf8_bom_comments_and_spaces() {
        let content = concat!(
            "\u{feff}; generated by test\n",
            "movie part 1.mkv   deadbeef\n",
            "über file.bin CAFEBABE\n",
            "\n"
        );

        let records = parse_sfv(content).unwrap();

        assert_eq!(
            records,
            vec![
                SfvRecord {
                    filename: "movie part 1.mkv".to_string(),
                    crc32: "DEADBEEF".to_string(),
                },
                SfvRecord {
                    filename: "über file.bin".to_string(),
                    crc32: "CAFEBABE".to_string(),
                },
            ]
        );
    }

    #[test]
    fn parse_sfv_rejects_invalid_crc32_values() {
        let err = parse_sfv("movie.mkv deadbee\n").unwrap_err();

        assert_eq!(err.kind(), io::ErrorKind::InvalidData);
        assert_eq!(
            err.to_string(),
            "SFV parse error on line 1: checksum must be exactly 8 hexadecimal characters"
        );
    }

    #[test]
    fn parse_sfv_rejects_tab_separators() {
        let err = parse_sfv("movie.mkv\tDEADBEEF\n").unwrap_err();

        assert_eq!(err.kind(), io::ErrorKind::InvalidData);
        assert_eq!(
            err.to_string(),
            "SFV parse error on line 1: tab characters are not valid in SFV entries"
        );
    }

    #[test]
    fn write_hash_file_round_trips_through_sfv_reader() {
        let output_dir = create_temp_dir("fileio-sfv-roundtrip");
        let output_path = output_dir.join("checksums.sfv");

        let mut first = FileEntry::default();
        first.filename = "movie part 1.mkv".to_string();
        first
            .hashes
            .insert(HashKind::CRC32, "deadbeef".to_string());

        let mut second = FileEntry::default();
        second.filename = "über file.bin".to_string();
        second
            .hashes
            .insert(HashKind::CRC32, "cafebabe".to_string());

        write_hash_file(&[first, second], &output_path, HashKind::CRC32, false).unwrap();

        let records = read_sfv_file(&output_path).unwrap();

        assert_eq!(
            records,
            vec![
                SfvRecord {
                    filename: "movie part 1.mkv".to_string(),
                    crc32: "DEADBEEF".to_string(),
                },
                SfvRecord {
                    filename: "über file.bin".to_string(),
                    crc32: "CAFEBABE".to_string(),
                },
            ]
        );

        fs::remove_dir_all(&output_dir).unwrap();
    }
}
